#include <stdint.h>
#include <math.h>
#include <stdio.h>
#include <errno.h>
#include <sys/stat.h>
#include <stdlib.h>

/* Linear congruential generator: updates state and returns next 32-bit value. */
static inline uint32_t lcg32_next(uint32_t *state) {
    const uint32_t a = 1664525u;
    const uint32_t c = 1013904223u;
    *state = a * (*state) + c;
    return *state;
}

/* Map the 32-bit integer output to a uniform number in [0, 1). */
static inline double lcg32_next_double(uint32_t *state) {
    return lcg32_next(state) / 4294967296.0;
}

static int compare_double(const void *pa, const void *pb)
{
    const double a = *(const double *)pa;
    const double b = *(const double *)pb;
    if (a < b) {
        return -1;
    }
    if (a > b) {
        return 1;
    }
    return 0;
}

/*
 * Write coin toss convergence data to file:
 *   toss_index running_fraction_of_heads
 */
static int run_coin_toss_experiment(const char *output_path, int n, uint32_t seed)
{
    FILE *fp = fopen(output_path, "w");
    int heads = 0;
    uint32_t state = seed;

    if (!fp) {
        fprintf(stderr, "Cannot open %s for writing\n", output_path);
        return 1;
    }

    /* Heads = 1 if U < 0.5, tails = 0 otherwise. */
    for (int i = 1; i <= n; ++i) {
        double u = lcg32_next_double(&state);
        int toss = (u < 0.5) ? 1 : 0;
        heads += toss;
        /* Running estimator for P(heads). */
        fprintf(fp, "%d %.10f\n", i, (double)heads / i);
    }

    fclose(fp);
    fprintf(stderr,
            "Coin tosses: final heads fraction after %d tosses = %.6f\n",
            n,
            (double)heads / n);
    return 0;
}

/*
 * Estimate pi with Monte Carlo using two independent RNG streams:
 * one stream for x and one stream for y.
 * Output columns:
 *   N pi_estimate abs_error
 */
static int run_pi_experiment_two_streams(const char *output_path)
{
    const int sample_sizes[] = {100, 300, 1000, 3000, 10000, 30000, 100000, 300000, 1000000, 3000000, 10000000, 30000000};
    const int ns = (int)(sizeof(sample_sizes) / sizeof(sample_sizes[0]));
    const double pi_ref = acos(-1.0);
    FILE *fp = fopen(output_path, "w");
    uint32_t state_x = 362436069u;
    uint32_t state_y = 274657845u;
    int inside = 0;
    int current_n = 0;

    if (!fp) {
        fprintf(stderr, "Cannot open %s for writing\n", output_path);
        return 1;
    }

    /* Reuse samples cumulatively so each target N extends the previous one. */
    for (int i = 0; i < ns; ++i) {
        int target_n = sample_sizes[i];

        while (current_n < target_n) {
            /* Two independent streams generate x and y coordinates. */
            double x = lcg32_next_double(&state_x);
            double y = lcg32_next_double(&state_y);
            double r2 = x * x + y * y;

            /* Count points in the quarter unit circle. */
            if (r2 <= 1.0) {
                inside++;
            }
            current_n++;
        }

        /* pi ~= 4 * area(quarter-circle) ~= 4 * inside / N. */
        double pi_est = 4.0 * (double)inside / (double)current_n;
        double abs_err = fabs(pi_est - pi_ref);
        fprintf(fp, "%d %.10f %.10e\n", current_n, pi_est, abs_err);
    }

    fclose(fp);
    fprintf(stderr, "Pi experiment: wrote %d sample sizes to %s\n", ns, output_path);
    return 0;
}

/*
 * Generate U~Uniform(0,1), transform Y=U^2, and save Y samples.
 * Output format:
 *   u_sample y_square_sample y_exp_sample
 */
static int run_u_squared_experiment(const char *output_path, int n, uint32_t seed)
{
    FILE *fp = fopen(output_path, "w");
    uint32_t state = seed;
    const double lambda = 1.5; /* rate parameter for exponential distribution */

    if (!fp) {
        fprintf(stderr, "Cannot open %s for writing\n", output_path);
        return 1;
    }

    for (int i = 0; i < n; ++i) {
        double u = lcg32_next_double(&state);
        double y_square = u * u;
        double y_exp = -log(1.0 - u)/lambda;
        fprintf(fp, "%.12f %.12f %.12f\n", u, y_square, y_exp);
    }

    fclose(fp);
    fprintf(stderr, "U^2 experiment: wrote %d samples to %s\n", n, output_path);
    return 0;
}

/*
 * Build the empirical CDF for an exponential sample generated by inverse
 * transform, and write sorted points (x_i, i/n).
 */
static int run_exponential_empirical_cdf_experiment(
    const char *output_path,
    int n,
    double lambda,
    uint32_t seed)
{
    FILE *fp = fopen(output_path, "w");
    uint32_t state = seed;
    double *sample = NULL;

    if (!fp) {
        fprintf(stderr, "Cannot open %s for writing\n", output_path);
        return 1;
    }

    sample = (double *)malloc((size_t)n * sizeof(double));
    if (!sample) {
        fprintf(stderr, "Allocation failed in empirical CDF experiment\n");
        fclose(fp);
        return 1;
    }

    for (int i = 0; i < n; ++i) {
        double u = lcg32_next_double(&state);
        sample[i] = -log(1.0 - u) / lambda;
    }

    qsort(sample, (size_t)n, sizeof(double), compare_double);

    for (int i = 0; i < n; ++i) {
        fprintf(fp, "%.12f %.12f\n", sample[i], (double)(i + 1) / n);
    }

    free(sample);
    fclose(fp);
    fprintf(stderr, "Empirical CDF experiment: wrote %d points to %s\n", n, output_path);
    return 0;
}

int main(void)
{
    const int n_coin_tosses = 100000;
    const int n_u_squared_samples = 100000;
    const int n_empirical_cdf = 50000;
    const double lambda = 1.5;
    const char *output_dir = "./outputs";
    const char *coin_file = "./outputs/coin_running_fraction.txt";
    const char *pi_file = "./outputs/pi_error_vs_n.txt";
    const char *u_squared_file = "./outputs/u_squared_samples.txt";
    const char *empirical_cdf_file = "./outputs/exp_empirical_cdf.txt";

    if (mkdir(output_dir, 0755) != 0 && errno != EEXIST) {
        fprintf(stderr, "Cannot create output directory %s\n", output_dir);
        return 1;
    }

    /* 1) Coin-toss convergence experiment. */
    if (run_coin_toss_experiment(coin_file, n_coin_tosses, 123456789u) != 0) {
        return 1;
    }

    /* 2) Monte Carlo pi experiment with two RNG streams. */
    if (run_pi_experiment_two_streams(pi_file) != 0) {
        return 1;
    }

    /* 3) Transform sampling experiment: Y = U^2 with U~Uniform(0,1). */
    if (run_u_squared_experiment(u_squared_file, n_u_squared_samples, 987654321u) != 0) {
        return 1;
    }

    /* 4) Empirical CDF for the exponential sample from inverse transform. */
    if (run_exponential_empirical_cdf_experiment(
            empirical_cdf_file,
            n_empirical_cdf,
            lambda,
            246813579u) != 0) {
        return 1;
    }

    fprintf(stderr,
            "Saved coin data to %s, pi data to %s, U^2 data to %s, and empirical CDF to %s\n",
            coin_file,
            pi_file,
            u_squared_file,
            empirical_cdf_file);
    return 0;
}